// Every theme reuses the same puzzle skeleton (a note points to a year,
// the year is the code to a hidden lockbox, the lockbox holds a key, the
// key opens the way out) but re-skins every prop, texture, and light.

export const THEMES = [
  {
    id: "train",
    name: "Runaway Train",
    coverKind: "map",
    tagline: "The last car of a train nobody's driving anymore.",
    codes: ["1904", "1917", "1929"],
    stageLabels: ["Car 7", "Car 8", "Car 9"],
    palette: {
      fog: 0x100e12,
      ambient: 0x4a4a58,
      ambientIntensity: 1.25,
      lampColor: 0xffb066,
      lampIntensity: 3.4,
      fillColor: 0x6f83b8,
      fillIntensity: 1.05,
      glowColor: 0xfff0c0,
      glowIntensity: 0.9,
    },
    // An oil lantern resting on the back corner of the console, not a
    // ceiling light — a real physical prop rather than a floating glow.
    lampPosition: [-4.5, 1.0, -1.4],
    decor: [
      { type: "lanternProp", x: -4.5, y: 0.85, z: -1.4, glass: "#ffdca0" },
      { type: "wallTool", x: -4.85, y: 1.3, z: 2.0, ry: Math.PI / 2, tool: "valve", color: "#8a8f94" },
      { type: "crateStack", x: -3.8, z: -3.6, base: "#33261a", band: "#6b5a3a" },
      { type: "barrel", x: 3.4, z: -3.6, color: "#4a3d2a", count: 2 },
    ],
    wall: { fn: "panelWallTexture", base: "#3a3d42", accent: "#22262a" },
    floor: { fn: "floorTexture", base: "#4a3524" },
    ceiling: { base: "#1b1a1e" },
    desk: { label: "control console", woodBase: "#2c2f33" },
    note: {
      lines: [
        "MANIFEST — CAR 7",
        "",
        '"Override code: first',
        "two stamped on the",
        "boiler plate, last two",
        "stenciled inside the",
        'crate — if you can force',
        'it open."',
      ],
      bg: "#d8cfa8",
      textColor: "#241f14",
      font: "monospace",
    },
    plaque: {
      title: "BOILER PLATE",
      subtitle: "Manufactured",
      bg: "#8a8f94",
      border: "#2c2f33",
      textColor: "#1a1c1e",
      font: "monospace",
    },
    tag: { bg: "#c7c2b0", textColor: "#1a1c1e", border: "#2c2f33" },
    rackLabel: "luggage rack",
    crate: { label: "luggage crate", deniedText: "The latch is rusted shut. You'll need something to pry it loose.", openToast: "You wedge the pry bar under the latch — it pops open.", base: "#33261a", band: "#6b5a3a" },
    tool: { label: "Pry Bar" },
    painting: {
      label: "route map",
      interactText: "[E] Pull the map aside",
      revealToast: "A signal box, bolted to the wall.",
    },
    safe: { label: "signal box", base: "#454a4f", dial: "#a8adb2" },
    key: { label: "Brake Release Key" },
    door: {
      label: "coupling door",
      lockedText: "It's locked. You need a key.",
      lockedPrompt: "[E] Try door",
      unlockPrompt: "[E] Release coupling",
      advanceToast: "You climb through into the next car.",
      openToast: "The coupling releases. The car rolls to a stop.",
    },
    ambiance: "shake",
  },

  {
    id: "mine",
    name: "Abandoned Mine Shaft",
    coverKind: "plank",
    tagline: "Shaft 9 — sealed for decades, until now.",
    codes: ["1912", "1925", "1938"],
    stageLabels: ["Level 1", "Level 2", "Level 3"],
    palette: {
      fog: 0x0e0c09,
      ambient: 0x3a342c,
      ambientIntensity: 0.95,
      lampColor: 0xd8ecff,
      lampIntensity: 2.6,
      fillColor: 0x5a5040,
      fillIntensity: 0.55,
      glowColor: 0xffdca0,
      glowIntensity: 0.6,
    },
    // A battery lantern sitting on a low crate beside the supply crate,
    // not a lamp overhead — a real prop, not a floating glow.
    lampPosition: [-2.8, 0.65, -1.2],
    decor: [
      { type: "pedestal", x: -2.8, z: -1.2, h: 0.5, base: "#141414", band: "#2a2a2a" },
      { type: "lanternProp", x: -2.8, y: 0.5, z: -1.2, glass: "#dff2ff" },
      { type: "wallTool", x: -4.85, y: 1.6, z: 2.2, ry: Math.PI / 2, tool: "pickaxe", color: "#8a8f94" },
      { type: "wallTool", x: -4.85, y: 1.05, z: 2.6, ry: Math.PI / 2, tool: "shovel", color: "#6b5a3a" },
      { type: "chain", x: -3, y: 1.5, z: -4.85 },
      { type: "crateStack", x: 3.6, z: -3.6, base: "#3a2c1a", band: "#c9a13a" },
    ],
    wall: { fn: "rockWallTexture", base: "#4a4038" },
    floor: { fn: "rockFloorTexture", base: "#332b22" },
    ceiling: { base: "#100e0a" },
    desk: { label: "supply crate", woodBase: "#3d2f20" },
    note: {
      lines: [
        "FOREMAN'S LOG",
        "",
        '"Lockbox code: first',
        "half carved into the",
        "support beam, second",
        "half chalked inside the",
        'crate — good luck opening',
        'it without tools."',
      ],
      bg: "#cbb98a",
      textColor: "#2a2013",
      font: "Georgia, serif",
    },
    plaque: {
      title: "SUPPORT BEAM",
      subtitle: "Carved",
      bg: "#5a4530",
      border: "#2a2013",
      textColor: "#f0dfb0",
      font: "Georgia, serif",
    },
    tag: { bg: "#3a2c1a", textColor: "#f0dfb0", border: "#1a120a" },
    rackLabel: "tool rack",
    crate: { label: "explosives crate", deniedText: "Sealed tight. You'll need a pickaxe to break the seal.", openToast: "You crack the seal open with the pickaxe.", base: "#3a2c1a", band: "#c9a13a" },
    tool: { label: "Pickaxe" },
    painting: {
      label: "loose plank",
      interactText: "[E] Pry the plank loose",
      revealToast: "A rusted lockbox, wedged in the rock.",
    },
    safe: { label: "lockbox", base: "#4a4238", dial: "#c9a13a" },
    key: { label: "Elevator Key" },
    door: {
      label: "mine lift gate",
      lockedText: "The lift won't budge without its key.",
      lockedPrompt: "[E] Try lift gate",
      unlockPrompt: "[E] Call the lift",
      advanceToast: "The lift drops you a level deeper.",
      openToast: "The lift creaks upward, toward daylight.",
    },
    ambiance: "headlamp",
  },

  {
    id: "submarine",
    name: "Self-Destruct Submarine",
    coverKind: "chart",
    tagline: "USS Kestrel — the countdown already started.",
    codes: ["1963", "1971", "1989"],
    stageLabels: ["Compartment 1", "Compartment 2", "Compartment 3"],
    palette: {
      fog: 0x0e0808,
      ambient: 0x3a2e2e,
      ambientIntensity: 1.1,
      lampColor: 0xff5a3a,
      lampIntensity: 2.9,
      fillColor: 0x6a808f,
      fillIntensity: 0.95,
      glowColor: 0xff8a5a,
      glowIntensity: 0.75,
    },
    // A battle lantern bolted to the wall, not a floating glow.
    lampPosition: [-4.85, 1.6, 0.8],
    decor: [
      { type: "lanternProp", x: -4.85, y: 1.45, z: 0.8, glass: "#ff5a3a" },
      { type: "wallTool", x: 4.85, y: 1.4, z: 2.0, ry: -Math.PI / 2, tool: "valve", color: "#9aa2a6" },
      { type: "crateStack", x: -3.8, z: -3.6, base: "#232c2f", band: "#5a6a6f" },
      { type: "barrel", x: 3.4, z: -3.6, color: "#2e3336", count: 1 },
    ],
    wall: { fn: "panelWallTexture", base: "#333c40", accent: "#1a2226" },
    floor: { fn: "metalFloorTexture", base: "#2e3336" },
    ceiling: { base: "#151a1c" },
    desk: { label: "navigation console", woodBase: "#232c2f" },
    note: {
      lines: [
        "OVERRIDE NOTICE",
        "",
        '"Code: first two from',
        "the hull plaque, last",
        "two stenciled inside",
        'the torpedo locker,',
        'if it\'ll open."',
      ],
      bg: "#c7d0d2",
      textColor: "#141b1d",
      font: "monospace",
    },
    plaque: {
      title: "HULL PLAQUE",
      subtitle: "Commissioned",
      bg: "#7a8a8f",
      border: "#1a2226",
      textColor: "#0e1315",
      font: "monospace",
    },
    tag: { bg: "#232c2f", textColor: "#ff5a3a", border: "#0e1315" },
    rackLabel: "gear locker",
    crate: { label: "torpedo locker", deniedText: "The locker's jammed shut. Needs a wrench to force the latch.", openToast: "You wrench the latch loose.", base: "#232c2f", band: "#5a6a6f" },
    tool: { label: "Pipe Wrench" },
    painting: {
      label: "sonar chart",
      interactText: "[E] Unclip the chart",
      revealToast: "A security panel, blinking red.",
    },
    safe: { label: "security panel", base: "#3a4448", dial: "#ff5a3a" },
    key: { label: "Hatch Release Key" },
    door: {
      label: "escape hatch",
      lockedText: "Sealed. You need the release key.",
      lockedPrompt: "[E] Try hatch",
      unlockPrompt: "[E] Blow the hatch",
      advanceToast: "You dog the hatch shut behind you and push forward.",
      openToast: "The hatch blows open — you're clear.",
    },
    ambiance: "alarm",
  },

  {
    id: "castle",
    name: "Medieval Castle Escape",
    coverKind: "tapestry",
    tagline: "Blackthorn Keep, and a door that hasn't opened in years.",
    codes: ["1147", "1189", "1215"],
    stageLabels: ["Outer Chamber", "Middle Chamber", "Vault Chamber"],
    palette: {
      fog: 0x0e0b07,
      ambient: 0x483c2e,
      ambientIntensity: 1.15,
      lampColor: 0xff9a4a,
      lampIntensity: 3.2,
      fillColor: 0x6a5a3a,
      fillIntensity: 0.85,
      glowColor: 0xffb066,
      glowIntensity: 0.75,
    },
    // A candle lantern resting on the writing desk.
    lampPosition: [-4.5, 1.0, -1.4],
    decor: [
      { type: "lanternProp", x: -4.5, y: 0.85, z: -1.4, glass: "#ffb066" },
      { type: "wallTool", x: -4.85, y: 1.7, z: 2.2, ry: Math.PI / 2, tool: "sword", color: "#9aa0a4" },
      { type: "chain", x: 3, y: 1.5, z: -4.85, ry: Math.PI },
      { type: "crateStack", x: 3.6, z: -3.6, base: "#2e2416", band: "#8a7245" },
    ],
    wall: { fn: "stoneWallTexture", base: "#5a554c" },
    floor: { fn: "stoneFloorTexture", base: "#4a453e" },
    ceiling: { base: "#171310" },
    desk: { label: "writing desk", woodBase: "#3d2b1f" },
    note: {
      lines: [
        "A SCRAP OF",
        "PARCHMENT",
        "",
        '"The vault remembers',
        "two halves: the founding",
        "stone bears the first,",
        "the armory chest the",
        'rest — once it is opened."',
      ],
      bg: "#e3d3a8",
      textColor: "#2b2010",
      font: "Georgia, serif",
    },
    plaque: {
      title: "FOUNDING STONE",
      subtitle: "Laid in the year",
      bg: "#8a8172",
      border: "#3a2e1f",
      textColor: "#241d12",
      font: "Georgia, serif",
    },
    tag: { bg: "#2e2416", textColor: "#c9a25a", border: "#1a1006" },
    rackLabel: "tapestry rack",
    crate: { label: "armory chest", deniedText: "Bound in iron — you'll need something to pry the strap loose.", openToast: "You pry the iron strap loose.", base: "#2e2416", band: "#8a7245" },
    tool: { label: "Iron Bar" },
    painting: {
      label: "tapestry",
      interactText: "[E] Pull the tapestry aside",
      revealToast: "A stone vault, set into the wall.",
    },
    safe: { label: "stone vault", base: "#57503f", dial: "#c9a25a" },
    key: { label: "Iron Key" },
    door: {
      label: "portcullis gate",
      lockedText: "Barred shut. It needs the iron key.",
      lockedPrompt: "[E] Try gate",
      unlockPrompt: "[E] Raise the portcullis",
      advanceToast: "You push through into the next chamber.",
      openToast: "The gate grinds open. You're free.",
    },
    ambiance: "torches",
  },
];

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
